"""
Policy Recommendation model storing evidence-grounded planner dossiers generated by Gemini 3.6.
"""
import uuid
from datetime import datetime, timezone
from typing import Optional
from sqlmodel import SQLModel, Field

class PolicyRecommendation(SQLModel, table=True):
    __tablename__ = "policy_recommendations"

    id: str = Field(default_factory=lambda: str(uuid.uuid4()), primary_key=True)
    cluster_id: str = Field(foreign_key="clusters.id", index=True)
    country_code: str = Field(default="IND", index=True)
    title: str
    summary: str
    action_type: str = Field(default="infrastructure_repair")  # infrastructure_repair, resource_allocation, policy_reform
    priority_score: float
    estimated_budget: Optional[float] = Field(default=None, nullable=True)
    currency: str = Field(default="INR")
    evidence_summary_json: str = Field(default="{}")           # Serialized JSON of underlying demand counts, coordinates, demographics
    status: str = Field(default="drafted")                    # drafted, approved, rejected, implemented
    created_by: Optional[str] = Field(default=None, nullable=True)
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"))
    reviewed_at: Optional[str] = Field(default=None, nullable=True)
