"""initial_schema

Revision ID: f0ea6a746f49
Revises: 
Create Date: 2026-07-17 01:10:15.510258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ea6a746f49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_action_drafts_cluster_id'), 'action_drafts', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_escalations_draft_id'), 'escalations', ['draft_id'], unique=False)
    op.create_index(op.f('ix_impact_summaries_cluster_id'), 'impact_summaries', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_issues_cluster_id'), 'issues', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_cluster_id'), table_name='issues')
    op.drop_index(op.f('ix_impact_summaries_cluster_id'), table_name='impact_summaries')
    op.drop_index(op.f('ix_escalations_draft_id'), table_name='escalations')
    op.drop_index(op.f('ix_action_drafts_cluster_id'), table_name='action_drafts')
    # ### end Alembic commands ###
